# Generated by Django 2.0.6 on 2018-06-30 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hunt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('blocked', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameUserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_used', models.PositiveSmallIntegerField(default=0)),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('feed', models.CharField(blank=True, max_length=1000, null=True)),
                ('game_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_user', to='hunt.GameUser')),
            ],
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hint_1', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_2', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_3', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_4', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_5', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_6', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_7', models.CharField(blank=True, max_length=100, null=True)),
                ('hint_8', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(default=1)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('ques_type', models.CharField(blank=True, max_length=10, null=True)),
                ('score', models.IntegerField(default=0)),
                ('answer', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='hint',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='question_hint', to='hunt.Question'),
        ),
        migrations.AddField(
            model_name='gameuserdata',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_question', to='hunt.Question'),
        ),
    ]
