# Generated by Django 2.0.6 on 2018-06-30 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0003_gameuserdata_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuserdata',
            name='game_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game_user_data', to='hunt.GameUser'),
        ),
    ]
