# Generated by Django 2.0.6 on 2018-07-01 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0004_auto_20180701_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameuserdata',
            name='game_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_user_data', to='hunt.GameUser'),
        ),
        migrations.AlterField(
            model_name='gameuserdata',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='on_question', to='hunt.Question'),
        ),
    ]
