# Generated by Django 2.0.6 on 2018-07-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0005_auto_20180701_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='hint',
            name='hint_5_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hint',
            name='hint_6_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hint',
            name='hint_7_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hint',
            name='hint_8_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hint',
            name='no_of_hints',
            field=models.IntegerField(default=0),
        ),
    ]
