# Generated by Django 2.0.6 on 2018-07-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0006_auto_20180701_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuserdata',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
