# Generated by Django 2.0.6 on 2018-07-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0007_gameuserdata_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='total_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
