# Generated by Django 2.0.6 on 2018-07-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0008_gameuser_total_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hint',
            name='hint_5_used',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='hint_6_used',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='hint_7_used',
        ),
        migrations.RemoveField(
            model_name='hint',
            name='hint_8_used',
        ),
        migrations.AddField(
            model_name='gameuserdata',
            name='hint_5_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuserdata',
            name='hint_6_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuserdata',
            name='hint_7_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gameuserdata',
            name='hint_8_used',
            field=models.BooleanField(default=False),
        ),
    ]
