# Generated by Django 2.0.6 on 2018-07-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0009_auto_20180701_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sattempts',
            field=models.IntegerField(default=0),
        ),
    ]
