# Generated by Django 2.0.7 on 2018-07-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0010_question_sattempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameuser',
            name='last_attempt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='gameuser',
            name='timeout_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
