# Generated by Django 2.0.7 on 2018-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hunt', '0011_auto_20180727_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
